# Generated by Django 3.1.1 on 2020-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
