# Generated by Django 3.1.1 on 2020-09-11 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20200911_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='upvoated',
            field=models.ManyToManyField(related_name='news_upvoated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=newsapp.models.User.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
